# Generated by Django 3.0.5 on 2020-08-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_analyze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='images',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
